//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareInformation.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardwareInformation.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more arguments contain errors! Exiting the program.
        /// </summary>
        internal static string ARGS_ERROR {
            get {
                return ResourceManager.GetString("ARGS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication error! Exiting the program.
        /// </summary>
        internal static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid credentials. Try again..
        /// </summary>
        internal static string AUTH_INVALID {
            get {
                return ResourceManager.GetString("AUTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (Update firmware).
        /// </summary>
        internal static string BIOS_VERSION_ALERT {
            get {
                return ResourceManager.GetString("BIOS_VERSION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware version:.
        /// </summary>
        internal static string CLI_BIOS_VERSION_ALERT {
            get {
                return ResourceManager.GetString("CLI_BIOS_VERSION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Database connectivity: .
        /// </summary>
        internal static string CLI_DATABASE_REACH_ERROR {
            get {
                return ResourceManager.GetString("CLI_DATABASE_REACH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware type: .
        /// </summary>
        internal static string CLI_FIRMWARE_TYPE_ALERT {
            get {
                return ResourceManager.GetString("CLI_FIRMWARE_TYPE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hostname: .
        /// </summary>
        internal static string CLI_HOSTNAME_ALERT {
            get {
                return ResourceManager.GetString("CLI_HOSTNAME_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA/M.2 operating mode: .
        /// </summary>
        internal static string CLI_MEDIA_OPERATION_ALERT {
            get {
                return ResourceManager.GetString("CLI_MEDIA_OPERATION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM amount and number of slots: .
        /// </summary>
        internal static string CLI_MEMORY_ALERT {
            get {
                return ResourceManager.GetString("CLI_MEMORY_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IP address: .
        /// </summary>
        internal static string CLI_NETWORK_IP_ERROR {
            get {
                return ResourceManager.GetString("CLI_NETWORK_IP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAC address: .
        /// </summary>
        internal static string CLI_NETWORK_MAC_ERROR {
            get {
                return ResourceManager.GetString("CLI_NETWORK_MAC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Secure Boot: .
        /// </summary>
        internal static string CLI_SECURE_BOOT_ALERT {
            get {
                return ResourceManager.GetString("CLI_SECURE_BOOT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TPM version: .
        /// </summary>
        internal static string CLI_TPM_ALERT {
            get {
                return ResourceManager.GetString("CLI_TPM_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Virtualization Technology: .
        /// </summary>
        internal static string CLI_VT_ALERT {
            get {
                return ResourceManager.GetString("CLI_VT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error contacting the database, check your intranet connection and that the web server is up!.
        /// </summary>
        internal static string DATABASE_REACH_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_REACH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  days since the last.
        /// </summary>
        internal static string DAYS_PASSED_TEXT {
            get {
                return ResourceManager.GetString("DAYS_PASSED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CHANGE-NAME.
        /// </summary>
        internal static string DEFAULT_HOSTNAME {
            get {
                return ResourceManager.GetString("DEFAULT_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee.
        /// </summary>
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collect Again.
        /// </summary>
        internal static string FETCH_AGAIN {
            get {
                return ResourceManager.GetString("FETCH_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collecting....
        /// </summary>
        internal static string FETCHING {
            get {
                return ResourceManager.GetString("FETCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Wrong firmware type).
        /// </summary>
        internal static string FIRMWARE_TYPE_ALERT {
            get {
                return ResourceManager.GetString("FIRMWARE_TYPE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fix the following issues before proceeding:.
        /// </summary>
        internal static string FIX_PROBLEMS {
            get {
                return ResourceManager.GetString("FIX_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a formatting.
        /// </summary>
        internal static string FORMAT_TEXT {
            get {
                return ResourceManager.GetString("FORMAT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Incorrect name, change).
        /// </summary>
        internal static string HOSTNAME_ALERT {
            get {
                return ResourceManager.GetString("HOSTNAME_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It is not possible to register for a date in the future..
        /// </summary>
        internal static string INCORRECT_FUTURE_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_FUTURE_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration date prior to the last maintenance date..
        /// </summary>
        internal static string INCORRECT_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Automatically selecting theme.
        /// </summary>
        internal static string LOG_AUTOTHEME_CHANGE {
            get {
                return ResourceManager.GetString("LOG_AUTOTHEME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware version.
        /// </summary>
        internal static string LOG_BIOS {
            get {
                return ResourceManager.GetString("LOG_BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware type.
        /// </summary>
        internal static string LOG_BIOSTYPE {
            get {
                return ResourceManager.GetString("LOG_BIOSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brand.
        /// </summary>
        internal static string LOG_BM {
            get {
                return ResourceManager.GetString("LOG_BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking presence of WebView2 Runtime on the system.
        /// </summary>
        internal static string LOG_CHECKING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_CHECKING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arguments detected, starting in CLI mode. list of arguments.
        /// </summary>
        internal static string LOG_CLI_MODE {
            get {
                return ResourceManager.GetString("LOG_CLI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ending program sequence.
        /// </summary>
        internal static string LOG_CLOSING_CLI {
            get {
                return ResourceManager.GetString("LOG_CLOSING_CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizing login form.
        /// </summary>
        internal static string LOG_CLOSING_LOGINFORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_LOGINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizing main form.
        /// </summary>
        internal static string LOG_CLOSING_MAINFORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_MAINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching to dark mode.
        /// </summary>
        internal static string LOG_DARKMODE_CHANGE {
            get {
                return ResourceManager.GetString("LOG_DARKMODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Completion of hardware collection.
        /// </summary>
        internal static string LOG_END_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_END_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime loading finished.
        /// </summary>
        internal static string LOG_END_LOADING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_END_LOADING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Getting file with hardware model information.
        /// </summary>
        internal static string LOG_FETCHING_BIOSFILE {
            get {
                return ResourceManager.GetString("LOG_FETCHING_BIOSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching available buildings and types of hardware.
        /// </summary>
        internal static string LOG_FETCHING_SERVER_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_SERVER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Video card and vRAM.
        /// </summary>
        internal static string LOG_GPUINFO {
            get {
                return ResourceManager.GetString("LOG_GPUINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Missing arguments, starting in GUI mode.
        /// </summary>
        internal static string LOG_GUI_MODE {
            get {
                return ResourceManager.GetString("LOG_GUI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compliant configuration, ready for registration.
        /// </summary>
        internal static string LOG_HARDWARE_PASSED {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage (total space).
        /// </summary>
        internal static string LOG_HDSIZE {
            get {
                return ResourceManager.GetString("LOG_HDSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hostname.
        /// </summary>
        internal static string LOG_HOSTNAME {
            get {
                return ResourceManager.GetString("LOG_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Starting registration process.
        /// </summary>
        internal static string LOG_INIT_REGISTRY {
            get {
                return ResourceManager.GetString("LOG_INIT_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Installing WebView2 Runtime.
        /// </summary>
        internal static string LOG_INSTALLING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_INSTALLING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NIC&apos;s IP Address.
        /// </summary>
        internal static string LOG_IP {
            get {
                return ResourceManager.GetString("LOG_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching to light mode.
        /// </summary>
        internal static string LOG_LIGHTMODE_CHANGE {
            get {
                return ResourceManager.GetString("LOG_LIGHTMODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NIC&apos;s MAC Address.
        /// </summary>
        internal static string LOG_MAC {
            get {
                return ResourceManager.GetString("LOG_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA/M.2 operating mode.
        /// </summary>
        internal static string LOG_MEDIAOP {
            get {
                return ResourceManager.GetString("LOG_MEDIAOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Storage type.
        /// </summary>
        internal static string LOG_MEDIATYPE {
            get {
                return ResourceManager.GetString("LOG_MEDIATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Model.
        /// </summary>
        internal static string LOG_MODEL {
            get {
                return ResourceManager.GetString("LOG_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Offline execution mode.
        /// </summary>
        internal static string LOG_OFFLINE_MODE {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server is OFFLINE.
        /// </summary>
        internal static string LOG_OFFLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server is ONLINE.
        /// </summary>
        internal static string LOG_ONLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_ONLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opening event log.
        /// </summary>
        internal static string LOG_OPENING_LOG {
            get {
                return ResourceManager.GetString("LOG_OPENING_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operating system.
        /// </summary>
        internal static string LOG_OS {
            get {
                return ResourceManager.GetString("LOG_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Issues detected in the configuration.
        /// </summary>
        internal static string LOG_PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("LOG_PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking server availability.
        /// </summary>
        internal static string LOG_PINGGING_SERVER {
            get {
                return ResourceManager.GetString("LOG_PINGGING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM amount and number of slots.
        /// </summary>
        internal static string LOG_PM {
            get {
                return ResourceManager.GetString("LOG_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processor and number of cores.
        /// </summary>
        internal static string LOG_PROCNAME {
            get {
                return ResourceManager.GetString("LOG_PROCNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering on the Asset Control Server.
        /// </summary>
        internal static string LOG_REGISTERING {
            get {
                return ResourceManager.GetString("LOG_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration finished.
        /// </summary>
        internal static string LOG_REGISTRY_FINISHED {
            get {
                return ResourceManager.GetString("LOG_REGISTRY_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalculating last formatting date.
        /// </summary>
        internal static string LOG_RESETTING_INSTALLDATE {
            get {
                return ResourceManager.GetString("LOG_RESETTING_INSTALLDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalculating last maintenance date.
        /// </summary>
        internal static string LOG_RESETTING_MAINTENANCEDATE {
            get {
                return ResourceManager.GetString("LOG_RESETTING_MAINTENANCEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more &apos;same&apos; arguments detected, however there is no existing record for the current asset. Computer must be registered first via GUI or via CLI with all command line options correctly filled in.
        /// </summary>
        internal static string LOG_SAMEWORD_NOFIRSTREGISTRY {
            get {
                return ResourceManager.GetString("LOG_SAMEWORD_NOFIRSTREGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Secure Boot.
        /// </summary>
        internal static string LOG_SECBOOT {
            get {
                return ResourceManager.GetString("LOG_SECBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serial Number.
        /// </summary>
        internal static string LOG_SERIALNO {
            get {
                return ResourceManager.GetString("LOG_SERIALNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server and port.
        /// </summary>
        internal static string LOG_SERVER_DETAIL {
            get {
                return ResourceManager.GetString("LOG_SERVER_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Displaying list of commands.
        /// </summary>
        internal static string LOG_SHOWING_HELP {
            get {
                return ResourceManager.GetString("LOG_SHOWING_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a S.M.A.R.T. status.
        /// </summary>
        internal static string LOG_SMART {
            get {
                return ResourceManager.GetString("LOG_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collecting hardware.
        /// </summary>
        internal static string LOG_START_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_START_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Starting loading of WebView2 Runtime.
        /// </summary>
        internal static string LOG_START_LOADING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_START_LOADING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Initializing collection procedure thread.
        /// </summary>
        internal static string LOG_START_THREAD {
            get {
                return ResourceManager.GetString("LOG_START_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Using dark theme.
        /// </summary>
        internal static string LOG_THEME {
            get {
                return ResourceManager.GetString("LOG_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TPM version.
        /// </summary>
        internal static string LOG_TPM {
            get {
                return ResourceManager.GetString("LOG_TPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accessing asset control system.
        /// </summary>
        internal static string LOG_VIEW_SERVER {
            get {
                return ResourceManager.GetString("LOG_VIEW_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Virtualization Technology.
        /// </summary>
        internal static string LOG_VT {
            get {
                return ResourceManager.GetString("LOG_VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime is already installed.
        /// </summary>
        internal static string LOG_WEBVIEW2_ALREADY_INSTALLED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_ALREADY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime installation failed, please try again.
        /// </summary>
        internal static string LOG_WEBVIEW2_INSTALL_FAILED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_INSTALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime successfully installed.
        /// </summary>
        internal static string LOG_WEBVIEW2_INSTALLED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime not found.
        /// </summary>
        internal static string LOG_WEBVIEW2_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a maintenance.
        /// </summary>
        internal static string MAINTENANCE_TEXT {
            get {
                return ResourceManager.GetString("MAINTENANCE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the required fields.
        /// </summary>
        internal static string MANDATORY_FIELD {
            get {
                return ResourceManager.GetString("MANDATORY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Incorrect operating mode, change).
        /// </summary>
        internal static string MEDIA_OPERATION_ALERT {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE/Legacy or RAID.
        /// </summary>
        internal static string MEDIA_OPERATION_IDE_RAID {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_IDE_RAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe.
        /// </summary>
        internal static string MEDIA_OPERATION_NVME {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_NVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Computer not connected to the Intranet.
        /// </summary>
        internal static string NETWORK_ERROR {
            get {
                return ResourceManager.GetString("NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Insufficient memory).
        /// </summary>
        internal static string NOT_ENOUGH_MEMORY {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  occupied.
        /// </summary>
        internal static string occupied {
            get {
                return ResourceManager.GetString("occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFFLINE.
        /// </summary>
        internal static string OFFLINE {
            get {
                return ResourceManager.GetString("OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFFLINE Mode!.
        /// </summary>
        internal static string OFFLINE_MODE_ACTIVATED {
            get {
                return ResourceManager.GetString("OFFLINE_MODE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ONLINE.
        /// </summary>
        internal static string ONLINE {
            get {
                return ResourceManager.GetString("ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolve issues displayed in red!.
        /// </summary>
        internal static string PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register / Update data.
        /// </summary>
        internal static string REGISTER_AGAIN {
            get {
                return ResourceManager.GetString("REGISTER_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering / Updating, please wait....
        /// </summary>
        internal static string REGISTERING {
            get {
                return ResourceManager.GetString("REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a With battery change.
        /// </summary>
        internal static string replacedBattery {
            get {
                return ResourceManager.GetString("replacedBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No battery change.
        /// </summary>
        internal static string sameBattery {
            get {
                return ResourceManager.GetString("sameBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Enable secure boot).
        /// </summary>
        internal static string SECURE_BOOT_ALERT {
            get {
                return ResourceManager.GetString("SECURE_BOOT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To access, select the server and the port!.
        /// </summary>
        internal static string SERVER_PORT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_PORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (Could not determine date of last service).
        /// </summary>
        internal static string SINCE_UNKNOWN {
            get {
                return ResourceManager.GetString("SINCE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  slots of .
        /// </summary>
        internal static string slots_of {
            get {
                return ResourceManager.GetString("slots_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Drive with imminent failure).
        /// </summary>
        internal static string SMART_FAIL {
            get {
                return ResourceManager.GetString("SMART_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student.
        /// </summary>
        internal static string student {
            get {
                return ResourceManager.GetString("student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Too much memory).
        /// </summary>
        internal static string TOO_MUCH_MEMORY {
            get {
                return ResourceManager.GetString("TOO_MUCH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (TPM disabled/incorrect version).
        /// </summary>
        internal static string TPM_ERROR {
            get {
                return ResourceManager.GetString("TPM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Enable Virtualization Technology in firmware).
        /// </summary>
        internal static string VT_ALERT {
            get {
                return ResourceManager.GetString("VT_ALERT", resourceCulture);
            }
        }
    }
}
