//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareInformation.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardwareInformation.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string AAAString1 {
            get {
                return ResourceManager.GetString("AAAString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more arguments contain errors! Exiting the program.
        /// </summary>
        public static string ARGS_ERROR {
            get {
                return ResourceManager.GetString("ARGS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication error! Exiting the program.
        /// </summary>
        public static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid credentials. Try again..
        /// </summary>
        public static string AUTH_INVALID {
            get {
                return ResourceManager.GetString("AUTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (Update firmware).
        /// </summary>
        public static string BIOS_VERSION_ALERT {
            get {
                return ResourceManager.GetString("BIOS_VERSION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware version:.
        /// </summary>
        public static string CLI_BIOS_VERSION_ALERT {
            get {
                return ResourceManager.GetString("CLI_BIOS_VERSION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Database connectivity: .
        /// </summary>
        public static string CLI_DATABASE_REACH_ERROR {
            get {
                return ResourceManager.GetString("CLI_DATABASE_REACH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware type: .
        /// </summary>
        public static string CLI_FIRMWARE_TYPE_ALERT {
            get {
                return ResourceManager.GetString("CLI_FIRMWARE_TYPE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hostname: .
        /// </summary>
        public static string CLI_HOSTNAME_ALERT {
            get {
                return ResourceManager.GetString("CLI_HOSTNAME_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA/M.2 operating mode: .
        /// </summary>
        public static string CLI_MEDIA_OPERATION_ALERT {
            get {
                return ResourceManager.GetString("CLI_MEDIA_OPERATION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM amount and number of slots: .
        /// </summary>
        public static string CLI_MEMORY_ALERT {
            get {
                return ResourceManager.GetString("CLI_MEMORY_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IP address: .
        /// </summary>
        public static string CLI_NETWORK_IP_ERROR {
            get {
                return ResourceManager.GetString("CLI_NETWORK_IP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAC address: .
        /// </summary>
        public static string CLI_NETWORK_MAC_ERROR {
            get {
                return ResourceManager.GetString("CLI_NETWORK_MAC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Secure Boot: .
        /// </summary>
        public static string CLI_SECURE_BOOT_ALERT {
            get {
                return ResourceManager.GetString("CLI_SECURE_BOOT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TPM version: .
        /// </summary>
        public static string CLI_TPM_ALERT {
            get {
                return ResourceManager.GetString("CLI_TPM_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Virtualization Technology: .
        /// </summary>
        public static string CLI_VT_ALERT {
            get {
                return ResourceManager.GetString("CLI_VT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error contacting the database, check your intranet connection and that the web server is up!.
        /// </summary>
        public static string DATABASE_REACH_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_REACH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  days since the last.
        /// </summary>
        public static string DAYS_PASSED_TEXT {
            get {
                return ResourceManager.GetString("DAYS_PASSED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CHANGE-NAME.
        /// </summary>
        public static string DEFAULT_HOSTNAME {
            get {
                return ResourceManager.GetString("DEFAULT_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collect Again.
        /// </summary>
        public static string FETCH_AGAIN {
            get {
                return ResourceManager.GetString("FETCH_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collecting....
        /// </summary>
        public static string FETCHING {
            get {
                return ResourceManager.GetString("FETCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Wrong firmware type).
        /// </summary>
        public static string FIRMWARE_TYPE_ALERT {
            get {
                return ResourceManager.GetString("FIRMWARE_TYPE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fix the following issues before proceeding:.
        /// </summary>
        public static string FIX_PROBLEMS {
            get {
                return ResourceManager.GetString("FIX_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a formatting.
        /// </summary>
        public static string FORMAT_TEXT {
            get {
                return ResourceManager.GetString("FORMAT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Incorrect name, change).
        /// </summary>
        public static string HOSTNAME_ALERT {
            get {
                return ResourceManager.GetString("HOSTNAME_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It is not possible to register for a date in the future..
        /// </summary>
        public static string INCORRECT_FUTURE_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_FUTURE_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration date prior to the last maintenance date..
        /// </summary>
        public static string INCORRECT_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_ALREADY_REGISTERED_TODAY {
            get {
                return ResourceManager.GetString("LOG_ALREADY_REGISTERED_TODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Automatically selecting theme.
        /// </summary>
        public static string LOG_AUTOTHEME_CHANGE {
            get {
                return ResourceManager.GetString("LOG_AUTOTHEME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware version.
        /// </summary>
        public static string LOG_BIOS {
            get {
                return ResourceManager.GetString("LOG_BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware type.
        /// </summary>
        public static string LOG_BIOSTYPE {
            get {
                return ResourceManager.GetString("LOG_BIOSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_BIOSVER_ERROR {
            get {
                return ResourceManager.GetString("LOG_BIOSVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_BM {
            get {
                return ResourceManager.GetString("LOG_BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking presence of WebView2 Runtime on the system.
        /// </summary>
        public static string LOG_CHECKING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_CHECKING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arguments detected, starting in CLI mode. list of arguments.
        /// </summary>
        public static string LOG_CLI_MODE {
            get {
                return ResourceManager.GetString("LOG_CLI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ending program sequence.
        /// </summary>
        public static string LOG_CLOSING_CLI {
            get {
                return ResourceManager.GetString("LOG_CLOSING_CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizing login form.
        /// </summary>
        public static string LOG_CLOSING_LOGINFORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_LOGINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizing main form.
        /// </summary>
        public static string LOG_CLOSING_MAINFORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_MAINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching to dark mode.
        /// </summary>
        public static string LOG_DARKMODE_CHANGE {
            get {
                return ResourceManager.GetString("LOG_DARKMODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in DEBUG mode.
        /// </summary>
        public static string LOG_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LOG_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Completion of hardware collection.
        /// </summary>
        public static string LOG_END_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_END_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime loading finished.
        /// </summary>
        public static string LOG_END_LOADING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_END_LOADING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Getting file with hardware model information.
        /// </summary>
        public static string LOG_FETCHING_BIOSFILE {
            get {
                return ResourceManager.GetString("LOG_FETCHING_BIOSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching available buildings and types of hardware.
        /// </summary>
        public static string LOG_FETCHING_SERVER_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_SERVER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_FILENAME_CP {
            get {
                return ResourceManager.GetString("LOG_FILENAME_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_FIRMWARE_ERROR {
            get {
                return ResourceManager.GetString("LOG_FIRMWARE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_GPUINFO {
            get {
                return ResourceManager.GetString("LOG_GPUINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Missing arguments, starting in GUI mode.
        /// </summary>
        public static string LOG_GUI_MODE {
            get {
                return ResourceManager.GetString("LOG_GUI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_HARDWARE_PASSED {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_HDSIZE {
            get {
                return ResourceManager.GetString("LOG_HDSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_HOSTNAME {
            get {
                return ResourceManager.GetString("LOG_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_HOSTNAME_ERROR {
            get {
                return ResourceManager.GetString("LOG_HOSTNAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_INCORRECT_FUTURE_REGISTER_DATE {
            get {
                return ResourceManager.GetString("LOG_INCORRECT_FUTURE_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_INCORRECT_REGISTER_DATE {
            get {
                return ResourceManager.GetString("LOG_INCORRECT_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start of execution.
        /// </summary>
        public static string LOG_INIT {
            get {
                return ResourceManager.GetString("LOG_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authenticating user.
        /// </summary>
        public static string LOG_INIT_LOGIN {
            get {
                return ResourceManager.GetString("LOG_INIT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Starting registration process.
        /// </summary>
        public static string LOG_INIT_REGISTRY {
            get {
                return ResourceManager.GetString("LOG_INIT_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Installing WebView2 Runtime.
        /// </summary>
        public static string LOG_INSTALLING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_INSTALLING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NIC&apos;s IP Address.
        /// </summary>
        public static string LOG_IP {
            get {
                return ResourceManager.GetString("LOG_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Switching to light mode.
        /// </summary>
        public static string LOG_LIGHTMODE_CHANGE {
            get {
                return ResourceManager.GetString("LOG_LIGHTMODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication failed.
        /// </summary>
        public static string LOG_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOG_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_LOGIN_INCOMPLETE {
            get {
                return ResourceManager.GetString("LOG_LOGIN_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication performed successfully.
        /// </summary>
        public static string LOG_LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_LOGOUT {
            get {
                return ResourceManager.GetString("LOG_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MAC {
            get {
                return ResourceManager.GetString("LOG_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MANDATORY_FIELD_ERROR {
            get {
                return ResourceManager.GetString("LOG_MANDATORY_FIELD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MEDIAOP {
            get {
                return ResourceManager.GetString("LOG_MEDIAOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MEDIAOP_ERROR {
            get {
                return ResourceManager.GetString("LOG_MEDIAOP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MEDIATYPE {
            get {
                return ResourceManager.GetString("LOG_MEDIATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MEMORYFEW_ERROR {
            get {
                return ResourceManager.GetString("LOG_MEMORYFEW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MEMORYMUCH_ERROR {
            get {
                return ResourceManager.GetString("LOG_MEMORYMUCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_MODEL {
            get {
                return ResourceManager.GetString("LOG_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_NETWORK_ERROR {
            get {
                return ResourceManager.GetString("LOG_NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_NO_INTRANET {
            get {
                return ResourceManager.GetString("LOG_NO_INTRANET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_OFFLINE_ERROR {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_OFFLINE_MODE {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server is OFFLINE.
        /// </summary>
        public static string LOG_OFFLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server is ONLINE.
        /// </summary>
        public static string LOG_ONLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_ONLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_OPENING_LOG {
            get {
                return ResourceManager.GetString("LOG_OPENING_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_OS {
            get {
                return ResourceManager.GetString("LOG_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_PC_DROPPED {
            get {
                return ResourceManager.GetString("LOG_PC_DROPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pending issues detected.
        /// </summary>
        public static string LOG_PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("LOG_PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking server availability.
        /// </summary>
        public static string LOG_PINGGING_SERVER {
            get {
                return ResourceManager.GetString("LOG_PINGGING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_PM {
            get {
                return ResourceManager.GetString("LOG_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_PROCNAME {
            get {
                return ResourceManager.GetString("LOG_PROCNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering on the Asset Control Server.
        /// </summary>
        public static string LOG_REGISTERING {
            get {
                return ResourceManager.GetString("LOG_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration finished.
        /// </summary>
        public static string LOG_REGISTRY_FINISHED {
            get {
                return ResourceManager.GetString("LOG_REGISTRY_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Running in RELEASE mode.
        /// </summary>
        public static string LOG_RELEASE_MODE {
            get {
                return ResourceManager.GetString("LOG_RELEASE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalculating last formatting date.
        /// </summary>
        public static string LOG_RESETTING_INSTALLDATE {
            get {
                return ResourceManager.GetString("LOG_RESETTING_INSTALLDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalculating last maintenance date.
        /// </summary>
        public static string LOG_RESETTING_MAINTENANCEDATE {
            get {
                return ResourceManager.GetString("LOG_RESETTING_MAINTENANCEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more &apos;same&apos; arguments detected, however there is no existing record for the current asset. Computer must be registered first via GUI or via CLI with all command line options correctly filled in.
        /// </summary>
        public static string LOG_SAMEWORD_NOFIRSTREGISTRY {
            get {
                return ResourceManager.GetString("LOG_SAMEWORD_NOFIRSTREGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Secure Boot.
        /// </summary>
        public static string LOG_SECBOOT {
            get {
                return ResourceManager.GetString("LOG_SECBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_SECBOOT_ERROR {
            get {
                return ResourceManager.GetString("LOG_SECBOOT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_SERIALNO {
            get {
                return ResourceManager.GetString("LOG_SERIALNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Server and port.
        /// </summary>
        public static string LOG_SERVER_DETAIL {
            get {
                return ResourceManager.GetString("LOG_SERVER_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_SERVER_UNREACHABLE {
            get {
                return ResourceManager.GetString("LOG_SERVER_UNREACHABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Displaying list of commands.
        /// </summary>
        public static string LOG_SHOWING_HELP {
            get {
                return ResourceManager.GetString("LOG_SHOWING_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_SMART {
            get {
                return ResourceManager.GetString("LOG_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_SMART_ERROR {
            get {
                return ResourceManager.GetString("LOG_SMART_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collecting hardware.
        /// </summary>
        public static string LOG_START_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_START_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Starting loading of WebView2 Runtime.
        /// </summary>
        public static string LOG_START_LOADING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_START_LOADING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_START_THREAD {
            get {
                return ResourceManager.GetString("LOG_START_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Using dark theme.
        /// </summary>
        public static string LOG_THEME {
            get {
                return ResourceManager.GetString("LOG_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TPM version.
        /// </summary>
        public static string LOG_TPM {
            get {
                return ResourceManager.GetString("LOG_TPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_TPM_ERROR {
            get {
                return ResourceManager.GetString("LOG_TPM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accessing asset control system.
        /// </summary>
        public static string LOG_VIEW_SERVER {
            get {
                return ResourceManager.GetString("LOG_VIEW_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Virtualization Technology.
        /// </summary>
        public static string LOG_VT {
            get {
                return ResourceManager.GetString("LOG_VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string LOG_VT_ERROR {
            get {
                return ResourceManager.GetString("LOG_VT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime is already installed.
        /// </summary>
        public static string LOG_WEBVIEW2_ALREADY_INSTALLED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_ALREADY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime installation failed, please try again.
        /// </summary>
        public static string LOG_WEBVIEW2_INSTALL_FAILED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_INSTALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime successfully installed.
        /// </summary>
        public static string LOG_WEBVIEW2_INSTALLED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WebView2 Runtime not found.
        /// </summary>
        public static string LOG_WEBVIEW2_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Found log file, adding information.
        /// </summary>
        public static string LOGFILE_EXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nonexistent log file, creating new file.
        /// </summary>
        public static string LOGFILE_NOTEXISTS {
            get {
                return ResourceManager.GetString("LOGFILE_NOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a maintenance.
        /// </summary>
        public static string MAINTENANCE_TEXT {
            get {
                return ResourceManager.GetString("MAINTENANCE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the required fields.
        /// </summary>
        public static string MANDATORY_FIELD {
            get {
                return ResourceManager.GetString("MANDATORY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Incorrect operating mode, change).
        /// </summary>
        public static string MEDIA_OPERATION_ALERT {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE/Legacy or RAID.
        /// </summary>
        public static string MEDIA_OPERATION_IDE_RAID {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_IDE_RAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe.
        /// </summary>
        public static string MEDIA_OPERATION_NVME {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_NVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Computer not connected to the Intranet.
        /// </summary>
        public static string NETWORK_ERROR {
            get {
                return ResourceManager.GetString("NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Insufficient memory).
        /// </summary>
        public static string NOT_ENOUGH_MEMORY {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFFLINE.
        /// </summary>
        public static string OFFLINE {
            get {
                return ResourceManager.GetString("OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFFLINE Mode!.
        /// </summary>
        public static string OFFLINE_MODE_ACTIVATED {
            get {
                return ResourceManager.GetString("OFFLINE_MODE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ONLINE.
        /// </summary>
        public static string ONLINE {
            get {
                return ResourceManager.GetString("ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equity written off, registration cancelled. Revert low and try again.
        /// </summary>
        public static string PC_DROPPED {
            get {
                return ResourceManager.GetString("PC_DROPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolve issues displayed in red!.
        /// </summary>
        public static string PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register / Update data.
        /// </summary>
        public static string REGISTER_AGAIN {
            get {
                return ResourceManager.GetString("REGISTER_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering / Updating, please wait....
        /// </summary>
        public static string REGISTERING {
            get {
                return ResourceManager.GetString("REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a With battery change.
        /// </summary>
        public static string replacedBattery {
            get {
                return ResourceManager.GetString("replacedBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No battery change.
        /// </summary>
        public static string sameBattery {
            get {
                return ResourceManager.GetString("sameBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Enable secure boot).
        /// </summary>
        public static string SECURE_BOOT_ALERT {
            get {
                return ResourceManager.GetString("SECURE_BOOT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To access, select the server and the port!.
        /// </summary>
        public static string SERVER_PORT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_PORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (Could not determine date of last service).
        /// </summary>
        public static string SINCE_UNKNOWN {
            get {
                return ResourceManager.GetString("SINCE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Drive with imminent failure).
        /// </summary>
        public static string SMART_FAIL {
            get {
                return ResourceManager.GetString("SMART_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student.
        /// </summary>
        public static string student {
            get {
                return ResourceManager.GetString("student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Too much memory).
        /// </summary>
        public static string TOO_MUCH_MEMORY {
            get {
                return ResourceManager.GetString("TOO_MUCH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (TPM disabled/incorrect version).
        /// </summary>
        public static string TPM_ERROR {
            get {
                return ResourceManager.GetString("TPM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Enable Virtualization Technology in firmware).
        /// </summary>
        public static string VT_ALERT {
            get {
                return ResourceManager.GetString("VT_ALERT", resourceCulture);
            }
        }
    }
}
