//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetInformationAndRegistration.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AirUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AirUIStrings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetInformationAndRegistration.Properties.AirUIStrings", typeof(AirUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Database connectivity: .
        /// </summary>
        internal static string ALERT_DATABASE_REACH_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_DATABASE_REACH_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware type: .
        /// </summary>
        internal static string ALERT_FIRMWARE_TYPE_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_FIRMWARE_TYPE_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change firmware type to.
        /// </summary>
        internal static string ALERT_FIRMWARE_TYPE_TO {
            get {
                return ResourceManager.GetString("ALERT_FIRMWARE_TYPE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Firmware version:.
        /// </summary>
        internal static string ALERT_FIRMWARE_VERSION_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_FIRMWARE_VERSION_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Update firmware to.
        /// </summary>
        internal static string ALERT_FIRMWARE_VERSION_TO {
            get {
                return ResourceManager.GetString("ALERT_FIRMWARE_VERSION_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Non-standard hostname.
        /// </summary>
        internal static string ALERT_HOSTNAME {
            get {
                return ResourceManager.GetString("ALERT_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hostname: .
        /// </summary>
        internal static string ALERT_HOSTNAME_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_HOSTNAME_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SATA/M.2 operating mode: .
        /// </summary>
        internal static string ALERT_MEDIA_OPERATION_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_MEDIA_OPERATION_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change operation mode to.
        /// </summary>
        internal static string ALERT_MEDIA_OPERATION_TO {
            get {
                return ResourceManager.GetString("ALERT_MEDIA_OPERATION_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RAM amount and number of slots: .
        /// </summary>
        internal static string ALERT_MEMORY_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_MEMORY_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Computer not connected to the Intranet.
        /// </summary>
        internal static string ALERT_NETWORK {
            get {
                return ResourceManager.GetString("ALERT_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IP address: .
        /// </summary>
        internal static string ALERT_NETWORK_IP_ERROR_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_NETWORK_IP_ERROR_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAC address: .
        /// </summary>
        internal static string ALERT_NETWORK_MAC_ERROR_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_NETWORK_MAC_ERROR_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insufficient memory.
        /// </summary>
        internal static string ALERT_NOT_ENOUGH_MEMORY {
            get {
                return ResourceManager.GetString("ALERT_NOT_ENOUGH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable Secure Boot.
        /// </summary>
        internal static string ALERT_SECURE_BOOT {
            get {
                return ResourceManager.GetString("ALERT_SECURE_BOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Secure Boot: .
        /// </summary>
        internal static string ALERT_SECURE_BOOT_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_SECURE_BOOT_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a S.M.A.R.T. Status: .
        /// </summary>
        internal static string ALERT_SMART_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_SMART_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Too much memory.
        /// </summary>
        internal static string ALERT_TOO_MUCH_MEMORY {
            get {
                return ResourceManager.GetString("ALERT_TOO_MUCH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TPM version: .
        /// </summary>
        internal static string ALERT_TPM_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_TPM_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change TPM to.
        /// </summary>
        internal static string ALERT_TPM_TO {
            get {
                return ResourceManager.GetString("ALERT_TPM_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable Virtualization Technology.
        /// </summary>
        internal static string ALERT_VT {
            get {
                return ResourceManager.GetString("ALERT_VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Virtualization Technology: .
        /// </summary>
        internal static string ALERT_VT_CLI_TITLE {
            get {
                return ResourceManager.GetString("ALERT_VT_CLI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a One or more arguments contain errors! Exiting the program.
        /// </summary>
        internal static string ARGS_ERROR {
            get {
                return ResourceManager.GetString("ARGS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authentication error! Exiting the program.
        /// </summary>
        internal static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current hardware ID.
        /// </summary>
        internal static string CURRENT_HARDWARE_ID {
            get {
                return ResourceManager.GetString("CURRENT_HARDWARE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Database hardware ID.
        /// </summary>
        internal static string DATABASE_HARDWARE_ID {
            get {
                return ResourceManager.GetString("DATABASE_HARDWARE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  day(s) since the last .
        /// </summary>
        internal static string DAYS_PASSED_TEXT {
            get {
                return ResourceManager.GetString("DAYS_PASSED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Software created, developed and maintained by Kevin Costa. Programmed in C# using .NET Framework 4.8. Supported systems: Windows 7, 10 and 11.
        ///
        ///    • Copyright © 2023 Kevin Vinícius Teixeira Costa
        ///    • Repository (GitHub): https://github.com/Kevin64/asset-information-and-registration
        ///    • Dependencies repository (GitHub): https://github.com/Kevin64/Dependencies
        ///    • License: (MIT) https://github.com/Kevin64/asset-information-and-registration/blob/master/LICENSE
        ///
        ///This software must be used in conju [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee.
        /// </summary>
        internal static string EMPLOYEE {
            get {
                return ResourceManager.GetString("EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXIT.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collect Again.
        /// </summary>
        internal static string FETCH_AGAIN {
            get {
                return ResourceManager.GetString("FETCH_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Collecting....
        /// </summary>
        internal static string FETCHING {
            get {
                return ResourceManager.GetString("FETCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fix the issues before proceeding.
        /// </summary>
        internal static string FIX_PROBLEMS {
            get {
                return ResourceManager.GetString("FIX_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a formatting.
        /// </summary>
        internal static string FORMAT_TEXT {
            get {
                return ResourceManager.GetString("FORMAT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It is not possible to register for a date in the future..
        /// </summary>
        internal static string INCORRECT_FUTURE_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_FUTURE_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration date prior to the last maintenance date..
        /// </summary>
        internal static string INCORRECT_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a maintenance.
        /// </summary>
        internal static string MAINTENANCE_TEXT {
            get {
                return ResourceManager.GetString("MAINTENANCE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fill in the required fields.
        /// </summary>
        internal static string MANDATORY_FIELD {
            get {
                return ResourceManager.GetString("MANDATORY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE/Legacy or RAID.
        /// </summary>
        internal static string MEDIA_OPERATION_IDE_RAID {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_IDE_RAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe.
        /// </summary>
        internal static string MEDIA_OPERATION_NVME {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_NVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  occupied.
        /// </summary>
        internal static string OCCUPIED {
            get {
                return ResourceManager.GetString("OCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFFLINE.
        /// </summary>
        internal static string OFFLINE {
            get {
                return ResourceManager.GetString("OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OFFLINE Mode!.
        /// </summary>
        internal static string OFFLINE_MODE_ACTIVATED {
            get {
                return ResourceManager.GetString("OFFLINE_MODE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ONLINE.
        /// </summary>
        internal static string ONLINE {
            get {
                return ResourceManager.GetString("ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolve issues displayed in red!.
        /// </summary>
        internal static string PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Register / Update data.
        /// </summary>
        internal static string REGISTER_AGAIN {
            get {
                return ResourceManager.GetString("REGISTER_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registering / Updating, please wait....
        /// </summary>
        internal static string REGISTERING {
            get {
                return ResourceManager.GetString("REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a With battery change.
        /// </summary>
        internal static string REPLACED_BATTERY {
            get {
                return ResourceManager.GetString("REPLACED_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No battery change.
        /// </summary>
        internal static string SAME_BATTERY {
            get {
                return ResourceManager.GetString("SAME_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To access, select the server and the port!.
        /// </summary>
        internal static string SERVER_PORT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_PORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a service.
        /// </summary>
        internal static string SERVICE_TEXT {
            get {
                return ResourceManager.GetString("SERVICE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not determine date of last service.
        /// </summary>
        internal static string SINCE_UNKNOWN {
            get {
                return ResourceManager.GetString("SINCE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  slots of .
        /// </summary>
        internal static string SLOTS_OF {
            get {
                return ResourceManager.GetString("SLOTS_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imminent failure on drive .
        /// </summary>
        internal static string SMART_FAIL {
            get {
                return ResourceManager.GetString("SMART_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student.
        /// </summary>
        internal static string STUDENT {
            get {
                return ResourceManager.GetString("STUDENT", resourceCulture);
            }
        }
    }
}
