//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetInformationAndRegistration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetInformationAndRegistration.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string aaaPROJECTaaa {
            get {
                return ResourceManager.GetString("aaaPROJECTaaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more arguments contain errors! Exiting the program.
        /// </summary>
        internal static string ARGS_ERROR {
            get {
                return ResourceManager.GetString("ARGS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error! Exiting the program.
        /// </summary>
        internal static string AUTH_ERROR {
            get {
                return ResourceManager.GetString("AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials. Try again..
        /// </summary>
        internal static string AUTH_INVALID {
            get {
                return ResourceManager.GetString("AUTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Outdated firmware).
        /// </summary>
        internal static string BIOS_VERSION_ALERT {
            get {
                return ResourceManager.GetString("BIOS_VERSION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version:.
        /// </summary>
        internal static string CLI_BIOS_VERSION_ALERT {
            get {
                return ResourceManager.GetString("CLI_BIOS_VERSION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connectivity: .
        /// </summary>
        internal static string CLI_DATABASE_REACH_ERROR {
            get {
                return ResourceManager.GetString("CLI_DATABASE_REACH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware type: .
        /// </summary>
        internal static string CLI_FIRMWARE_TYPE_ALERT {
            get {
                return ResourceManager.GetString("CLI_FIRMWARE_TYPE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname: .
        /// </summary>
        internal static string CLI_HOSTNAME_ALERT {
            get {
                return ResourceManager.GetString("CLI_HOSTNAME_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATA/M.2 operating mode: .
        /// </summary>
        internal static string CLI_MEDIA_OPERATION_ALERT {
            get {
                return ResourceManager.GetString("CLI_MEDIA_OPERATION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM amount and number of slots: .
        /// </summary>
        internal static string CLI_MEMORY_ALERT {
            get {
                return ResourceManager.GetString("CLI_MEMORY_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address: .
        /// </summary>
        internal static string CLI_NETWORK_IP_ERROR {
            get {
                return ResourceManager.GetString("CLI_NETWORK_IP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address: .
        /// </summary>
        internal static string CLI_NETWORK_MAC_ERROR {
            get {
                return ResourceManager.GetString("CLI_NETWORK_MAC_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Boot: .
        /// </summary>
        internal static string CLI_SECURE_BOOT_ALERT {
            get {
                return ResourceManager.GetString("CLI_SECURE_BOOT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPM version: .
        /// </summary>
        internal static string CLI_TPM_ALERT {
            get {
                return ResourceManager.GetString("CLI_TPM_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtualization Technology: .
        /// </summary>
        internal static string CLI_VT_ALERT {
            get {
                return ResourceManager.GetString("CLI_VT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error contacting the database, check your intranet connection and that the web server is up!.
        /// </summary>
        internal static string DATABASE_REACH_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_REACH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days since the last .
        /// </summary>
        internal static string DAYS_PASSED_TEXT {
            get {
                return ResourceManager.GetString("DAYS_PASSED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE-NAME.
        /// </summary>
        internal static string DEFAULT_HOSTNAME {
            get {
                return ResourceManager.GetString("DEFAULT_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software created, developed and maintained by Kevin Costa. Programmed in C# using .NET Framework 4.8. Supported systems: Windows 7, 10 and 11.
        ///
        ///    • Copyright © 2023 Kevin Vinícius Teixeira Costa
        ///    • Repository (GitHub): https://github.com/Kevin64/asset-information-and-registration
        ///    • Dependencies repository (GitHub): https://github.com/Kevin64/Dependencies
        ///    • License: (MIT) https://github.com/Kevin64/asset-information-and-registration/blob/master/LICENSE
        ///
        ///This software must be used in conju [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string EMPLOYEE {
            get {
                return ResourceManager.GetString("EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Again.
        /// </summary>
        internal static string FETCH_AGAIN {
            get {
                return ResourceManager.GetString("FETCH_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting....
        /// </summary>
        internal static string FETCHING {
            get {
                return ResourceManager.GetString("FETCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Incorrect firmware type).
        /// </summary>
        internal static string FIRMWARE_TYPE_ALERT {
            get {
                return ResourceManager.GetString("FIRMWARE_TYPE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the following issues before proceeding:.
        /// </summary>
        internal static string FIX_PROBLEMS {
            get {
                return ResourceManager.GetString("FIX_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatting.
        /// </summary>
        internal static string FORMAT_TEXT {
            get {
                return ResourceManager.GetString("FORMAT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Incorrect name).
        /// </summary>
        internal static string HOSTNAME_ALERT {
            get {
                return ResourceManager.GetString("HOSTNAME_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to register for a date in the future..
        /// </summary>
        internal static string INCORRECT_FUTURE_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_FUTURE_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date prior to the last maintenance date..
        /// </summary>
        internal static string INCORRECT_REGISTER_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_REGISTER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory registered.
        /// </summary>
        internal static string LOG_AD_REGISTERED {
            get {
                return ResourceManager.GetString("LOG_AD_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically selecting theme.
        /// </summary>
        internal static string LOG_AUTOTHEME_CHANGE {
            get {
                return ResourceManager.GetString("LOG_AUTOTHEME_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        internal static string LOG_BIOS {
            get {
                return ResourceManager.GetString("LOG_BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware type.
        /// </summary>
        internal static string LOG_BIOSTYPE {
            get {
                return ResourceManager.GetString("LOG_BIOSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string LOG_BM {
            get {
                return ResourceManager.GetString("LOG_BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking presence of WebView2 Runtime on the system.
        /// </summary>
        internal static string LOG_CHECKING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_CHECKING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments detected, starting in CLI mode. list of arguments.
        /// </summary>
        internal static string LOG_CLI_MODE {
            get {
                return ResourceManager.GetString("LOG_CLI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending program sequence.
        /// </summary>
        internal static string LOG_CLOSING_CLI {
            get {
                return ResourceManager.GetString("LOG_CLOSING_CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing login form.
        /// </summary>
        internal static string LOG_CLOSING_LOGINFORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_LOGINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing main form.
        /// </summary>
        internal static string LOG_CLOSING_MAINFORM {
            get {
                return ResourceManager.GetString("LOG_CLOSING_MAINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching to dark mode.
        /// </summary>
        internal static string LOG_DARKMODE_CHANGE {
            get {
                return ResourceManager.GetString("LOG_DARKMODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion of hardware collection.
        /// </summary>
        internal static string LOG_END_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_END_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Runtime loading finished.
        /// </summary>
        internal static string LOG_END_LOADING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_END_LOADING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting file with hardware model information.
        /// </summary>
        internal static string LOG_FETCHING_BIOSFILE {
            get {
                return ResourceManager.GetString("LOG_FETCHING_BIOSFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching available buildings and types of hardware in the local file.
        /// </summary>
        internal static string LOG_FETCHING_LOCAL_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_LOCAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching available buildings and types of hardware.
        /// </summary>
        internal static string LOG_FETCHING_SERVER_DATA {
            get {
                return ResourceManager.GetString("LOG_FETCHING_SERVER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video card and vRAM.
        /// </summary>
        internal static string LOG_GPUINFO {
            get {
                return ResourceManager.GetString("LOG_GPUINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing arguments, starting in GUI mode.
        /// </summary>
        internal static string LOG_GUI_MODE {
            get {
                return ResourceManager.GetString("LOG_GUI_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliant configuration, ready for registration.
        /// </summary>
        internal static string LOG_HARDWARE_PASSED {
            get {
                return ResourceManager.GetString("LOG_HARDWARE_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage (total space).
        /// </summary>
        internal static string LOG_HDSIZE {
            get {
                return ResourceManager.GetString("LOG_HDSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        internal static string LOG_HOSTNAME {
            get {
                return ResourceManager.GetString("LOG_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting registration process.
        /// </summary>
        internal static string LOG_INIT_REGISTRY {
            get {
                return ResourceManager.GetString("LOG_INIT_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing WebView2 Runtime.
        /// </summary>
        internal static string LOG_INSTALLING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_INSTALLING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC&apos;s IP Address.
        /// </summary>
        internal static string LOG_IP {
            get {
                return ResourceManager.GetString("LOG_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching to light mode.
        /// </summary>
        internal static string LOG_LIGHTMODE_CHANGE {
            get {
                return ResourceManager.GetString("LOG_LIGHTMODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIC&apos;s MAC Address.
        /// </summary>
        internal static string LOG_MAC {
            get {
                return ResourceManager.GetString("LOG_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATA/M.2 operating mode.
        /// </summary>
        internal static string LOG_MEDIAOP {
            get {
                return ResourceManager.GetString("LOG_MEDIAOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage type.
        /// </summary>
        internal static string LOG_MEDIATYPE {
            get {
                return ResourceManager.GetString("LOG_MEDIATYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string LOG_MODEL {
            get {
                return ResourceManager.GetString("LOG_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline execution mode.
        /// </summary>
        internal static string LOG_OFFLINE_MODE {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is OFFLINE.
        /// </summary>
        internal static string LOG_OFFLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_OFFLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is ONLINE.
        /// </summary>
        internal static string LOG_ONLINE_SERVER {
            get {
                return ResourceManager.GetString("LOG_ONLINE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening event log.
        /// </summary>
        internal static string LOG_OPENING_LOG {
            get {
                return ResourceManager.GetString("LOG_OPENING_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system.
        /// </summary>
        internal static string LOG_OS {
            get {
                return ResourceManager.GetString("LOG_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues detected in the configuration.
        /// </summary>
        internal static string LOG_PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("LOG_PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking server availability.
        /// </summary>
        internal static string LOG_PINGGING_SERVER {
            get {
                return ResourceManager.GetString("LOG_PINGGING_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM amount and number of slots.
        /// </summary>
        internal static string LOG_PM {
            get {
                return ResourceManager.GetString("LOG_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor and number of cores.
        /// </summary>
        internal static string LOG_PROCNAME {
            get {
                return ResourceManager.GetString("LOG_PROCNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering on the Asset Control Server.
        /// </summary>
        internal static string LOG_REGISTERING {
            get {
                return ResourceManager.GetString("LOG_REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration finished.
        /// </summary>
        internal static string LOG_REGISTRY_FINISHED {
            get {
                return ResourceManager.GetString("LOG_REGISTRY_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculating last formatting date.
        /// </summary>
        internal static string LOG_RESETTING_INSTALLDATE {
            get {
                return ResourceManager.GetString("LOG_RESETTING_INSTALLDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculating last maintenance date.
        /// </summary>
        internal static string LOG_RESETTING_MAINTENANCEDATE {
            get {
                return ResourceManager.GetString("LOG_RESETTING_MAINTENANCEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more &apos;same&apos; arguments detected, however there is no existing record for the current asset. Computer must be registered first via GUI or via CLI with all command line options correctly filled in.
        /// </summary>
        internal static string LOG_SAMEWORD_NOFIRSTREGISTRY {
            get {
                return ResourceManager.GetString("LOG_SAMEWORD_NOFIRSTREGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Boot.
        /// </summary>
        internal static string LOG_SECBOOT {
            get {
                return ResourceManager.GetString("LOG_SECBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string LOG_SERIALNO {
            get {
                return ResourceManager.GetString("LOG_SERIALNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server and port.
        /// </summary>
        internal static string LOG_SERVER_DETAIL {
            get {
                return ResourceManager.GetString("LOG_SERVER_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying list of commands.
        /// </summary>
        internal static string LOG_SHOWING_HELP {
            get {
                return ResourceManager.GetString("LOG_SHOWING_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.M.A.R.T. status.
        /// </summary>
        internal static string LOG_SMART {
            get {
                return ResourceManager.GetString("LOG_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting hardware.
        /// </summary>
        internal static string LOG_START_COLLECTING {
            get {
                return ResourceManager.GetString("LOG_START_COLLECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting loading of WebView2 Runtime.
        /// </summary>
        internal static string LOG_START_LOADING_WEBVIEW2 {
            get {
                return ResourceManager.GetString("LOG_START_LOADING_WEBVIEW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing collection procedure thread.
        /// </summary>
        internal static string LOG_START_THREAD {
            get {
                return ResourceManager.GetString("LOG_START_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using dark theme.
        /// </summary>
        internal static string LOG_THEME {
            get {
                return ResourceManager.GetString("LOG_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPM version.
        /// </summary>
        internal static string LOG_TPM {
            get {
                return ResourceManager.GetString("LOG_TPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing asset control system.
        /// </summary>
        internal static string LOG_VIEW_SERVER {
            get {
                return ResourceManager.GetString("LOG_VIEW_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtualization Technology.
        /// </summary>
        internal static string LOG_VT {
            get {
                return ResourceManager.GetString("LOG_VT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Runtime is already installed.
        /// </summary>
        internal static string LOG_WEBVIEW2_ALREADY_INSTALLED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_ALREADY_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Runtime installation failed, please try again.
        /// </summary>
        internal static string LOG_WEBVIEW2_INSTALL_FAILED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_INSTALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Runtime successfully installed.
        /// </summary>
        internal static string LOG_WEBVIEW2_INSTALLED {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Runtime not found.
        /// </summary>
        internal static string LOG_WEBVIEW2_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_WEBVIEW2_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance.
        /// </summary>
        internal static string MAINTENANCE_TEXT {
            get {
                return ResourceManager.GetString("MAINTENANCE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the required fields.
        /// </summary>
        internal static string MANDATORY_FIELD {
            get {
                return ResourceManager.GetString("MANDATORY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Incorrect operation mode).
        /// </summary>
        internal static string MEDIA_OPERATION_ALERT {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDE/Legacy or RAID.
        /// </summary>
        internal static string MEDIA_OPERATION_IDE_RAID {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_IDE_RAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVMe.
        /// </summary>
        internal static string MEDIA_OPERATION_NVME {
            get {
                return ResourceManager.GetString("MEDIA_OPERATION_NVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer not connected to the Intranet.
        /// </summary>
        internal static string NETWORK_ERROR {
            get {
                return ResourceManager.GetString("NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Insufficient memory).
        /// </summary>
        internal static string NOT_ENOUGH_MEMORY {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  occupied.
        /// </summary>
        internal static string OCCUPIED {
            get {
                return ResourceManager.GetString("OCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE.
        /// </summary>
        internal static string OFFLINE {
            get {
                return ResourceManager.GetString("OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE Mode!.
        /// </summary>
        internal static string OFFLINE_MODE_ACTIVATED {
            get {
                return ResourceManager.GetString("OFFLINE_MODE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE.
        /// </summary>
        internal static string ONLINE {
            get {
                return ResourceManager.GetString("ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve issues displayed in red!.
        /// </summary>
        internal static string PENDENCY_ERROR {
            get {
                return ResourceManager.GetString("PENDENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register / Update data.
        /// </summary>
        internal static string REGISTER_AGAIN {
            get {
                return ResourceManager.GetString("REGISTER_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering / Updating, please wait....
        /// </summary>
        internal static string REGISTERING {
            get {
                return ResourceManager.GetString("REGISTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With battery change.
        /// </summary>
        internal static string REPLACED_BATTERY {
            get {
                return ResourceManager.GetString("REPLACED_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No battery change.
        /// </summary>
        internal static string SAME_BATTERY {
            get {
                return ResourceManager.GetString("SAME_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Secure Boot disabled).
        /// </summary>
        internal static string SECURE_BOOT_ALERT {
            get {
                return ResourceManager.GetString("SECURE_BOOT_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access, select the server and the port!.
        /// </summary>
        internal static string SERVER_PORT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_PORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Could not determine date of last service).
        /// </summary>
        internal static string SINCE_UNKNOWN {
            get {
                return ResourceManager.GetString("SINCE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  slots of .
        /// </summary>
        internal static string SLOTS_OF {
            get {
                return ResourceManager.GetString("SLOTS_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Drive with imminent failure).
        /// </summary>
        internal static string SMART_FAIL {
            get {
                return ResourceManager.GetString("SMART_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string STUDENT {
            get {
                return ResourceManager.GetString("STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Too much memory).
        /// </summary>
        internal static string TOO_MUCH_MEMORY {
            get {
                return ResourceManager.GetString("TOO_MUCH_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (TPM disabled/incorrect version).
        /// </summary>
        internal static string TPM_ERROR {
            get {
                return ResourceManager.GetString("TPM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Virtualization Technology disabled).
        /// </summary>
        internal static string VT_ALERT {
            get {
                return ResourceManager.GetString("VT_ALERT", resourceCulture);
            }
        }
    }
}
